[functions]
  directory = "netlify/functions"

[dev]
  command = "quasar dev"
  port = 8888
  targetPort = 9000
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
